### ISSUE TITLE
The cryptographic proof page is not being generated it states the claim can't be found in your wallet? Where am I getting the things wrong?

### ISSUE THREAD

**Issue by sanketsaboo** [codingwithmanny/polygonid-on-chain-verification#2]

**Comment by codingwithmanny** [comment]
@sanketsaboo please see this new README on things. There has been quite a lot of changes lately.
https://github.com/codingwithmanny/0xPolygonID--sh-id-platform/tree/docs/readme-walkthrough#getting-started
